[package]
name = "vacuum"
version = "0.1.0"
authors = ["ibrahim.dursun <ibrahim.dursun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
glob = "0.3.0"
dirs = "2"
pom = "3.0.2"
